import { AlertTriangle } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useWbOversightStats } from '../../hooks/whistleblowing-oversight';
import { wbRoutes } from '../../../../config/routes';
import { wbCategoryLabelOf, wbPriorityLabelOf, wbStatusLabelOf } from '../../../whistleblowing/utils/format';

function Distribution({ title, values, label }: { title: string; values: Record<string, number>; label: (value: string) => string }) { return <article className="source-chart-card"><h3>{title}</h3>{Object.entries(values).map(([key, count]) => <div className="chart-row" key={key}><div><span>{label(key)}</span><strong>{count}</strong></div><i style={{ width: `${Math.max(4, count * 12)}%` }} /></div>)}{Object.keys(values).length === 0 && <div className="source-state">No data to display yet.</div>}</article>; }
export function WhistleblowingOversightSection() { const { data: stats, isLoading, isError } = useWbOversightStats(); if (isLoading || isError || !stats) return null; return <section><div className="page-titlebar"><div><span className="source-eyebrow">Organization oversight</span><h2>Whistleblowing</h2><p>Confidential incident reporting and investigation portfolio.</p></div><Link className="source-button source-button-outline" to={wbRoutes.dashboard}>View dashboard</Link></div><div className="source-stat-grid source-stat-grid-four">{[['TOTAL REPORTS', stats.total], ['OPEN REPORTS', stats.open], ['UNDER INVESTIGATION', stats.underInvestigation], ['SLA AT RISK', stats.slaAtRisk]].map(([label, value]) => <article className="source-stat-card" key={String(label)}><span>{String(label)}</span><strong>{String(value)}</strong></article>)}</div><div className="source-chart-grid"><Distribution title="By status" values={stats.byStatus} label={wbStatusLabelOf} /><Distribution title="By category" values={stats.byCategory} label={wbCategoryLabelOf} /><Distribution title="By priority" values={stats.byPriority} label={wbPriorityLabelOf} /></div>{stats.slaBreached > 0 && <p className="source-error"><AlertTriangle size={16} /> {stats.slaBreached} report(s) have breached SLA.</p>}</section>; }

