import { FormEvent, useState } from 'react';
import axios from 'axios';

const api = axios.create({ baseURL: import.meta.env.VITE_API_BASE_URL || 'http://localhost:3001/api/v1' });
api.interceptors.request.use((config) => { const token = localStorage.getItem('wb.internalToken'); if (token) config.headers.Authorization = `Bearer ${token}`; return config; });

export function InternalWorkflowPanel({ caseId, status, priority, permissions }: { caseId: string; status: string; priority: string; permissions: string[] }) {
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const investigate = permissions.includes('whistleblowing_case:investigate'); const admin = permissions.includes('whistleblowing_case:admin');
  async function submit(path: string, body: Record<string, unknown>) { setBusy(true); setError(''); try { await api.post(`/whistleblowing/cases/${caseId}/${path}`, body); location.reload(); } catch (e) { setError(axios.isAxiosError(e) ? String(e.response?.data?.message ?? 'Action failed.') : 'Action failed.'); } finally { setBusy(false); } }
  function form(path: string, fields: React.ReactNode[], body: (data: FormData) => Record<string, unknown>, title: string) { return <form className="source-form" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); void submit(path, body(new FormData(event.currentTarget))); }}><h3>{title}</h3>{fields}<button className="source-button" disabled={busy}>{busy ? 'Saving…' : title}</button></form>; }
  return <section id="investigation" className="source-case-card"><h2>Investigation workflow</h2>{error && <p className="source-error">{error}</p>}
    {investigate && ['SUBMITTED', 'UNDER_TRIAGE'].includes(status) && form('triage', [<label key="priority">Priority<select name="priority" defaultValue={priority}><option>PRIORITY_LOW</option><option>PRIORITY_MEDIUM</option><option>PRIORITY_HIGH</option><option>PRIORITY_CRITICAL</option></select></label>, <label key="assessment">Preliminary assessment<textarea name="assessment" required minLength={10} /></label>], (d) => ({ priority: d.get('priority'), preliminaryAssessment: d.get('assessment') }), 'Triage case')}
    {investigate && ['SUBMITTED', 'UNDER_TRIAGE', 'UNDER_INVESTIGATION', 'WB_ESCALATED'].includes(status) && form('priority', [<label key="priority">Update priority<select name="priority" defaultValue={priority}><option>PRIORITY_LOW</option><option>PRIORITY_MEDIUM</option><option>PRIORITY_HIGH</option><option>PRIORITY_CRITICAL</option></select></label>], (d) => ({ priority: d.get('priority') }), 'Save priority')}
    {admin && ['SUBMITTED', 'UNDER_TRIAGE', 'UNDER_INVESTIGATION', 'WB_ESCALATED'].includes(status) && form('escalate', [<label key="reason">Escalation reason<textarea name="reason" required minLength={3} /></label>], (d) => ({ reason: d.get('reason') }), 'Escalate case')}
    {investigate && ['UNDER_INVESTIGATION', 'WB_ESCALATED'].includes(status) && form('resolve', [<label key="findings">Investigation findings<textarea name="findings" required minLength={10} /></label>, <label key="recommendation">Disciplinary recommendation<textarea name="recommendation" /></label>], (d) => ({ investigationFindings: d.get('findings'), disciplinaryRecommendation: d.get('recommendation') || undefined }), 'Resolve case')}
    {admin && status === 'RESOLVED' && <><h3>Closure</h3><form className="source-form" onSubmit={(event) => { event.preventDefault(); const d = new FormData(event.currentTarget); void submit('close', { closureOutcome: d.get('outcome'), dismiss: d.get('dismiss') === 'on' }); }}><label>Closure outcome<textarea name="outcome" required minLength={3} /></label><label className="check"><input name="dismiss" type="checkbox" /> Mark as dismissed</label><button className="source-button source-button-danger" disabled={busy}>Close case</button></form></>}
    {investigate && !['WB_CLOSED', 'WB_DISMISSED'].includes(status) && <form className="source-form" onSubmit={(event) => { event.preventDefault(); const d = new FormData(event.currentTarget); void submit('comments', { content: d.get('content'), isInternal: d.get('internal') === 'on' }); event.currentTarget.reset(); }}><h3>Messages and internal notes</h3><label>Message<textarea name="content" required minLength={1} /></label><label className="check"><input name="internal" type="checkbox" /> Internal note (hidden from reporter)</label><button className="source-button" disabled={busy}>Add message</button></form>}
  </section>;
}
