import { FormEvent, useEffect, useState } from 'react';
import axios from 'axios';
import { getAccessToken } from '@lib/auth-token';

const api = axios.create({ baseURL: import.meta.env.VITE_API_BASE_URL || 'http://localhost:3001/api/v1' });
api.interceptors.request.use(config => { const token = getAccessToken(); if (token) config.headers.Authorization = `Bearer ${token}`; return config; });
const errorText = (e: unknown) => axios.isAxiosError(e) ? String(e.response?.data?.message ?? 'Request failed.') : 'Request failed.';

export function CaseParityTools({ caseId, participants = [], relatedCaseIds = [], caseData, enabled }: { caseId: string; participants?: any[]; relatedCaseIds?: string[]; caseData?: any; enabled: boolean }) {
  const [error, setError] = useState('');
  const [editing, setEditing] = useState<any | null>(null);
  const [investigators, setInvestigators] = useState<any[]>([]);
  useEffect(() => {
    if (!enabled) return;
    api.get('/whistleblowing/cases/assignable-investigators', { params: { caseId } }).then(r => setInvestigators(Array.isArray(r.data) ? r.data : [])).catch(e => setError(errorText(e)));
  }, [caseId, enabled]);

  if (!enabled) return null;

  async function refreshAfter(request: Promise<unknown>) { try { await request; location.reload(); } catch (e) { setError(errorText(e)); } }
  async function post(path: string, body: Record<string, unknown>) { await refreshAfter(api.post(`/whistleblowing/cases/${caseId}/${path}`, body)); }
  async function patch(path: string, body: Record<string, unknown>) { await refreshAfter(api.patch(`/whistleblowing/cases/${caseId}/${path}`, body)); }
  async function unlink(id: string) { await refreshAfter(api.delete(`/whistleblowing/cases/${caseId}/link/${id}`)); }
  async function updateParticipant(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editing) return; const form = new FormData(event.currentTarget); await refreshAfter(api.patch(`/whistleblowing/cases/${caseId}/participants/${editing.id}`, { fullName: form.get('fullName'), jobTitle: form.get('jobTitle'), relationship: form.get('relationship'), role: form.get('role'), results: form.get('results') })); }
  async function removeParticipant(id: string) { if (!window.confirm('Remove this participant?')) return; await refreshAfter(api.delete(`/whistleblowing/cases/${caseId}/participants/${id}`)); }
  function addParticipant(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); void post('participants', { fullName: form.get('fullName'), jobTitle: form.get('jobTitle'), relationship: form.get('relationship'), role: form.get('role'), results: form.get('results') }); }

  return <section className="card"><h2>Investigation data</h2>
    <form onSubmit={e => { e.preventDefault(); const form = new FormData(e.currentTarget); void patch('details', { caseType: form.get('caseType'), intakeMethod: form.get('intakeMethod'), relationshipToOrg: form.get('relationshipToOrg') || undefined, incidentLocation: form.get('incidentLocation') || undefined, locationCity: form.get('locationCity') || undefined, locationState: form.get('locationState') || undefined, locationPostalCode: form.get('locationPostalCode') || undefined, locationCountry: form.get('locationCountry') || undefined, previouslyReported: form.get('previouslyReported') || undefined, whenLastOccurred: form.get('whenLastOccurred') || undefined, conductDuration: form.get('conductDuration') || undefined, awarenessSource: form.get('awarenessSource') || undefined }); }}>
      <h3>Classification and details</h3><div className="form-grid"><select name="caseType" defaultValue={caseData?.caseType ?? 'ALLEGATION'}><option>ALLEGATION</option><option>INQUIRY</option></select><select name="intakeMethod" defaultValue={caseData?.intakeMethod ?? 'WEB'}><option>WEB</option><option>EMAIL</option><option>PHONE</option><option>IN_PERSON</option><option>MAIL</option><option>OTHER_INTAKE</option></select><select name="relationshipToOrg" defaultValue={caseData?.relationshipToOrg ?? ''}><option value="">Relationship</option>{['EMPLOYEE','FORMER_EMPLOYEE','CONTRACTOR','VENDOR_SUPPLIER','CUSTOMER','BUSINESS_PARTNER','OTHER_RELATIONSHIP'].map(v => <option key={v}>{v}</option>)}</select></div>
      <div className="form-grid"><input name="incidentLocation" placeholder="Incident location" defaultValue={caseData?.incidentLocation ?? ''} /><input name="locationCity" placeholder="City" defaultValue={caseData?.locationCity ?? ''} /><input name="locationState" placeholder="State" defaultValue={caseData?.locationState ?? ''} /><input name="locationPostalCode" placeholder="Postal code" defaultValue={caseData?.locationPostalCode ?? ''} /><input name="locationCountry" placeholder="Country" defaultValue={caseData?.locationCountry ?? ''} /></div>
      <div className="form-grid"><select name="previouslyReported" defaultValue={caseData?.previouslyReported ?? ''}><option value="">Previously reported?</option><option>YES</option><option>NO</option><option>UNKNOWN</option></select><input name="whenLastOccurred" placeholder="When last occurred" defaultValue={caseData?.whenLastOccurred ?? ''} /><select name="conductDuration" defaultValue={caseData?.conductDuration ?? ''}><option value="">Conduct duration</option><option>ONE_TIME</option><option>LESS_THAN_MONTH</option><option>ONE_TO_THREE_MONTHS</option><option>THREE_TO_SIX_MONTHS</option><option>SIX_TO_TWELVE_MONTHS</option><option>OVER_A_YEAR</option><option>ONGOING</option><option>UNKNOWN_DURATION</option></select><select name="awarenessSource" defaultValue={caseData?.awarenessSource ?? ''}><option value="">Awareness source</option><option>WITNESSED</option><option>TOLD_BY_SOMEONE</option><option>REVIEWED_DOCUMENTS</option><option>RUMOR</option><option>INVOLVED</option><option>OTHER_SOURCE</option></select></div><button>Save classification</button>
    </form>
    <form onSubmit={e => { e.preventDefault(); const form = new FormData(e.currentTarget); void post('assign', { investigatorId: form.get('investigatorId') }); }}><h3>Assignment</h3><div className="form-grid"><select name="investigatorId" defaultValue={caseData?.assignedInvestigator?.id ?? ''} required><option value="">Choose investigator</option>{investigators.map(i => <option key={i.id} value={i.id}>{i.displayName}</option>)}</select><button disabled={!investigators.length}>Assign investigator</button></div></form>
    <form onSubmit={e => { e.preventDefault(); const form = new FormData(e.currentTarget); void patch('synopsis', { primaryOutcome: form.get('primaryOutcome') || undefined, secondaryOutcome: form.get('secondaryOutcome') || undefined, actionTaken: form.get('actionTaken') || undefined, potentialNextSteps: form.get('potentialNextSteps') || undefined, synopsisNotes: form.get('synopsisNotes') || undefined }); }}><h3>Case synopsis</h3><div className="form-grid"><input name="primaryOutcome" placeholder="Primary outcome" defaultValue={caseData?.primaryOutcome ?? ''} /><input name="secondaryOutcome" placeholder="Secondary outcome" defaultValue={caseData?.secondaryOutcome ?? ''} /><input name="actionTaken" placeholder="Action taken" defaultValue={caseData?.actionTaken ?? ''} /></div><textarea name="potentialNextSteps" placeholder="Potential next steps" defaultValue={caseData?.potentialNextSteps ?? ''} /><textarea name="synopsisNotes" placeholder="Synopsis notes" defaultValue={caseData?.synopsisNotes ?? ''} /><button>Save synopsis</button></form>
    <form onSubmit={e => { e.preventDefault(); const form = new FormData(e.currentTarget); void post('escalate', { reason: form.get('reason') }); }}><h3>Escalation</h3><div className="form-grid"><input name="reason" placeholder="Reason for escalation" required /><button>Escalate case</button></div></form>
    <h3>Participants</h3>{participants.map(p => <p key={p.id}><strong>{p.fullName || [p.firstName, p.lastName].filter(Boolean).join(' ') || 'Unnamed'}</strong> · {p.role}{p.relationship ? ` · ${p.relationship}` : ''} <button type="button" className="secondary" onClick={() => setEditing(p)}>Edit</button> <button type="button" className="secondary" onClick={() => void removeParticipant(p.id)}>Remove</button></p>)}
    <form onSubmit={addParticipant}><div className="form-grid"><input name="fullName" placeholder="Full name" required /><input name="jobTitle" placeholder="Job title" /><input name="relationship" placeholder="Relationship" /><select name="role" defaultValue="SUBJECT"><option>SUBJECT</option><option>WITNESS</option><option>REPORTER</option><option>OTHER_PARTICIPANT</option></select></div><textarea name="results" placeholder="Interview/results notes" /><button>Add participant</button></form>
    {editing && <form onSubmit={updateParticipant}><h4>Edit participant</h4><div className="form-grid"><input name="fullName" defaultValue={editing.fullName ?? ''} required /><input name="jobTitle" defaultValue={editing.jobTitle ?? ''} /><input name="relationship" defaultValue={editing.relationship ?? ''} /><select name="role" defaultValue={editing.role}><option>SUBJECT</option><option>WITNESS</option><option>REPORTER</option><option>OTHER_PARTICIPANT</option></select></div><textarea name="results" defaultValue={editing.results ?? ''} /><button>Save participant</button><button type="button" className="secondary" onClick={() => setEditing(null)}>Cancel</button></form>}
    <h3>Related cases</h3>{relatedCaseIds.length ? relatedCaseIds.map(id => <p key={id}><code>{id}</code> <button type="button" className="secondary" onClick={() => void unlink(id)}>Unlink</button></p>) : <p>No linked cases.</p>}<form onSubmit={e => { e.preventDefault(); const value = new FormData(e.currentTarget).get('relatedCaseId'); if (value) void post('link', { relatedCaseId: value }); }}><input name="relatedCaseId" placeholder="Related case public id" required /><button>Link case</button></form>{error && <p className="error">{error}</p>}
  </section>;
}
