import { useState, type ReactElement, type ReactNode } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Activity, Building2, CheckCircle2, Edit3, KeyRound, Layers3, Lock, Plus, Shield, Users } from 'lucide-react';
import type { AdminOrganization, AdminPermission, AdminRole, AdminSettings, AdminUser } from '@features/admin/api/admin.service';
import { adminService } from '@features/admin/api/admin.service';
import { Loader } from '@components/common/Loader';
import { PageTitle } from '@components/ui/page-title';
import { Button } from '@components/ui/button';
import { Badge } from '@components/ui/badge';
import { Input } from '@components/ui/input';
import { Label } from '@components/ui/label';
import { Sheet } from '@components/ui/sheet';
import { getApiErrorMessage } from '@lib/api-error';

function useAdminQuery<T>(key: string, queryFn: () => Promise<T>) { return useQuery({ queryKey: ['platform-admin', key], queryFn, retry: false }); }
function Frame({ eyebrow, title, subtitle, action, children }: { eyebrow?: string; title: string; subtitle?: string; action?: ReactNode; children: ReactNode }): ReactElement { return <div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div>{eyebrow && <p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-brand-accent">{eyebrow}</p>}<PageTitle className="mt-1 text-xl text-brand-primary">{title}</PageTitle>{subtitle && <p className="mt-1 max-w-3xl text-sm text-slate-500">{subtitle}</p>}</div>{action}</div>{children}</div>; }
function State({ loading, error, children }: { loading: boolean; error: unknown; children: ReactNode }): ReactElement { if (loading) return <Loader label="Loading system data..." />; if (error) return <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{getApiErrorMessage(error)}</div>; return <>{children}</>; }
function Table({ children }: { children: ReactNode }): ReactElement { return <div className="overflow-x-auto rounded-lg border border-slate-200 bg-white"><table className="w-full min-w-[760px] text-sm">{children}</table></div>; }
function TableHead({ children }: { children: ReactNode }): ReactElement { return <thead className="border-b border-slate-200 bg-slate-50 text-left text-[10px] uppercase tracking-wide text-slate-400"><tr>{children}</tr></thead>; }
function RoleBadge({ role }: { role: string }): ReactElement { const variant = role === 'ADMIN' ? 'danger' : role === 'TENANT' ? 'warning' : role === 'SUPPORT' ? 'info' : 'default'; return <Badge variant={variant}>{role}</Badge>; }
function LockedBadge({ locked }: { locked: boolean }): ReactElement { return <Badge variant={locked ? 'warning' : 'success'}>{locked ? <><Lock className="mr-1 h-3 w-3" />Locked</> : 'Editable'}</Badge>; }
function ActionError({ error }: { error: unknown }): ReactElement | null { return error ? <p className="rounded-md border border-red-200 bg-red-50 px-3 py-2 text-xs text-red-700">{getApiErrorMessage(error)}</p> : null; }
function Metric({ label, value, icon: Icon }: { label: string; value: string | number; icon: typeof Users }): ReactElement { return <article className="rounded-lg border border-slate-200 bg-white p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-medium uppercase tracking-wide text-slate-400">{label}</p><p className="mt-2 text-2xl font-semibold text-slate-900">{value}</p></div><span className="flex h-8 w-8 items-center justify-center rounded-md bg-[#e5f4f5] text-brand-accent"><Icon className="h-4 w-4" /></span></div></article>; }

export function AdminDashboardPage(): ReactElement { const q = useAdminQuery<{ organizations: number; users: number; permissions: number; roles: number; cases: number }>('dashboard', adminService.dashboard); return <Frame eyebrow="System Console" title="Welcome" subtitle="Platform-wide administration, organizations, licensing and access controls."><State loading={q.isLoading} error={q.error}>{q.data && <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Total organizations" value={q.data.organizations} icon={Building2} /><Metric label="Total users" value={q.data.users} icon={Users} /><Metric label="Active permissions" value={q.data.permissions} icon={KeyRound} /><Metric label="Roles" value={q.data.roles} icon={Shield} /><Metric label="Whistleblowing cases" value={q.data.cases} icon={Activity} /></div><div className="grid gap-4 lg:grid-cols-2"><section className="rounded-lg border border-slate-200 bg-white p-5"><div className="mb-4 flex items-center gap-2"><Layers3 className="h-4 w-4 text-brand-accent" /><h2 className="text-sm font-semibold text-slate-900">Executive overview</h2></div><p className="text-sm leading-relaxed text-slate-500">Super administrators can manage organizations, access roles, permissions, and platform user status from this console.</p></section><section className="rounded-lg border border-slate-200 bg-white p-5"><div className="mb-4 flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-brand-accent" /><h2 className="text-sm font-semibold text-slate-900">Access model</h2></div><div className="flex flex-wrap gap-2"><RoleBadge role="ADMIN" /><RoleBadge role="TENANT" /><RoleBadge role="USER" /></div></section></div></>}</State></Frame>; }

export function AdminOrganizationsPage(): ReactElement {
  const client = useQueryClient(); const q = useAdminQuery<AdminOrganization[]>('organizations', adminService.organizations); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<AdminOrganization | null>(null); const [name, setName] = useState(''); const [slug, setSlug] = useState(''); const [enabled, setEnabled] = useState(true);
  const save = useMutation({ mutationFn: () => editing ? adminService.updateOrganization(editing.id, { name: name.trim(), whistleblowingEnabled: enabled }) : adminService.createOrganization({ name: name.trim(), slug: slug.trim() }), onSuccess: () => { void client.invalidateQueries({ queryKey: ['platform-admin', 'organizations'] }); setOpen(false); setEditing(null); setName(''); setSlug(''); setEnabled(true); } });
  const startCreate = () => { setEditing(null); setName(''); setSlug(''); setEnabled(true); setOpen(true); }; const startEdit = (row: AdminOrganization) => { setEditing(row); setName(row.name); setSlug(row.slug); setEnabled(row.status === 'Active'); setOpen(true); };
  return <Frame eyebrow="System Console" title="Organizations" subtitle="Create and manage organization access boundaries." action={<Button className="gap-1" onClick={startCreate}><Plus className="h-4 w-4" />Create organization</Button>}><State loading={q.isLoading} error={q.error}>{q.data && <Table><TableHead><th className="px-4 py-3">Name</th><th className="px-4 py-3">Slug</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Members</th><th className="px-4 py-3">Cases</th><th className="px-4 py-3 text-right">Actions</th></TableHead><tbody className="divide-y divide-slate-100">{q.data.map((row) => <tr key={row.id} className="hover:bg-slate-50"><td className="px-4 py-3 font-medium text-slate-900">{row.name}</td><td className="px-4 py-3 text-slate-500">{row.slug}</td><td className="px-4 py-3"><Badge variant={row.status === 'Active' ? 'success' : 'default'}>{row.status}</Badge></td><td className="px-4 py-3 text-slate-600">{row.members}</td><td className="px-4 py-3 text-slate-600">{row.cases}</td><td className="px-4 py-3 text-right"><Button size="sm" variant="outline" onClick={() => startEdit(row)}><Edit3 className="h-3.5 w-3.5" />Edit</Button></td></tr>)}</tbody></Table>}</State><Sheet isOpen={open} onClose={() => setOpen(false)} title={editing ? 'Edit organization' : 'Create organization'} footer={<div className="flex justify-end gap-3"><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={() => save.mutate()} disabled={save.isPending || !name.trim() || (!editing && !slug.trim())}>{save.isPending ? 'Saving...' : 'Save'}</Button></div>}><div className="space-y-4"><div><Label htmlFor="org-name">Name</Label><Input id="org-name" value={name} onChange={(e) => setName(e.target.value)} /></div>{!editing && <div><Label htmlFor="org-slug">Slug</Label><Input id="org-slug" value={slug} onChange={(e) => setSlug(e.target.value.toLowerCase())} placeholder="organization-slug" /></div>}<label className="flex items-center gap-2 text-sm text-slate-700"><input type="checkbox" checked={enabled} onChange={(e) => setEnabled(e.target.checked)} />Whistleblowing enabled</label><ActionError error={save.error} /></div></Sheet></Frame>;
}

export function AdminPermissionsPage(): ReactElement {
  const client = useQueryClient(); const q = useAdminQuery<AdminPermission[]>('permissions', adminService.permissions); const [open, setOpen] = useState(false); const [resource, setResource] = useState(''); const [action, setAction] = useState('');
  const create = useMutation({ mutationFn: () => adminService.createPermission({ resource: resource.trim(), action: action.trim() }), onSuccess: () => { void client.invalidateQueries({ queryKey: ['platform-admin', 'permissions'] }); setOpen(false); setResource(''); setAction(''); } }); const update = useMutation({ mutationFn: (row: AdminPermission) => adminService.updatePermission(row.id, { isActive: !row.isActive }), onSuccess: () => void client.invalidateQueries({ queryKey: ['platform-admin', 'permissions'] }) });
  return <Frame eyebrow="Access control" title="Permissions" subtitle="Create platform permission keys and activate or deactivate editable permissions." action={<Button className="gap-1" onClick={() => setOpen(true)}><Plus className="h-4 w-4" />Create permission</Button>}><State loading={q.isLoading} error={q.error}>{q.data && <Table><TableHead><th className="px-4 py-3">Permission</th><th className="px-4 py-3">Resource</th><th className="px-4 py-3">Action</th><th className="px-4 py-3">Roles</th><th className="px-4 py-3">State</th><th className="px-4 py-3 text-right">Access</th></TableHead><tbody className="divide-y divide-slate-100">{q.data.map((row) => <tr key={row.id} className="hover:bg-slate-50"><td className="px-4 py-3 font-mono text-xs text-slate-700">{row.key}</td><td className="px-4 py-3 text-slate-600">{row.resource}</td><td className="px-4 py-3 text-slate-600">{row.action}</td><td className="px-4 py-3 text-slate-600">{row.roles}</td><td className="px-4 py-3"><div className="flex items-center gap-2"><LockedBadge locked={row.locked} /><Badge variant={row.isActive ? 'success' : 'default'}>{row.isActive ? 'Active' : 'Inactive'}</Badge></div></td><td className="px-4 py-3 text-right"><Button size="sm" variant="outline" disabled={row.locked || update.isPending} onClick={() => update.mutate(row)}>{row.isActive ? 'Disable' : 'Enable'}</Button></td></tr>)}</tbody></Table>}</State><Sheet isOpen={open} onClose={() => setOpen(false)} title="Create permission" description="Use a resource:action key for a platform capability." footer={<div className="flex justify-end gap-3"><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={() => create.mutate()} disabled={create.isPending || !resource.trim() || !action.trim()}>Create</Button></div>}><div className="space-y-4"><div><Label htmlFor="permission-resource">Resource</Label><Input id="permission-resource" value={resource} onChange={(e) => setResource(e.target.value.toLowerCase())} placeholder="whistleblowing_case" /></div><div><Label htmlFor="permission-action">Action</Label><Input id="permission-action" value={action} onChange={(e) => setAction(e.target.value.toLowerCase())} placeholder="read" /></div><ActionError error={create.error} /></div></Sheet></Frame>;
}

export function AdminRolesPage(): ReactElement {
  const client = useQueryClient(); const roles = useAdminQuery<AdminRole[]>('roles', adminService.roles); const organizations = useAdminQuery<AdminOrganization[]>('organizations', adminService.organizations); const permissions = useAdminQuery<AdminPermission[]>('permissions', adminService.permissions); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<AdminRole | null>(null); const [name, setName] = useState(''); const [organizationId, setOrganizationId] = useState(''); const [permissionIds, setPermissionIds] = useState<string[]>([]);
  const save = useMutation({ mutationFn: () => editing ? adminService.updateRole(editing.id, { name: name.trim(), permissionIds }) : adminService.createRole({ name: name.trim(), ...(organizationId ? { organizationId } : {}), permissionIds }), onSuccess: () => { void client.invalidateQueries({ queryKey: ['platform-admin', 'roles'] }); setOpen(false); setEditing(null); setName(''); setOrganizationId(''); setPermissionIds([]); } }); const startCreate = () => { setEditing(null); setName(''); setOrganizationId(''); setPermissionIds([]); setOpen(true); }; const startEdit = (row: AdminRole) => { if (row.locked) return; setEditing(row); setName(row.name); setOrganizationId(row.organizationId ?? ''); setPermissionIds(row.permissions.map((permission) => permission.id)); setOpen(true); };
  return <Frame eyebrow="Access control" title="Roles" subtitle="Create editable platform or organization roles and assign existing permissions." action={<Button className="gap-1" onClick={startCreate}><Plus className="h-4 w-4" />Create role</Button>}><State loading={roles.isLoading} error={roles.error}>{roles.data && <Table><TableHead><th className="px-4 py-3">Role</th><th className="px-4 py-3">Scope</th><th className="px-4 py-3">Permissions</th><th className="px-4 py-3">State</th><th className="px-4 py-3 text-right">Actions</th></TableHead><tbody className="divide-y divide-slate-100">{roles.data.map((row) => <tr key={row.id} className="hover:bg-slate-50"><td className="px-4 py-3 font-medium text-slate-900">{row.name}</td><td className="px-4 py-3 text-slate-600">{row.scope}</td><td className="px-4 py-3"><Badge variant={row.permissions.length ? 'success' : 'default'}>{row.permissions.length} permissions</Badge></td><td className="px-4 py-3"><LockedBadge locked={row.locked} /></td><td className="px-4 py-3 text-right"><Button size="sm" variant="outline" disabled={row.locked} onClick={() => startEdit(row)}><Edit3 className="h-3.5 w-3.5" />Edit</Button></td></tr>)}</tbody></Table>}</State><Sheet isOpen={open} onClose={() => setOpen(false)} title={editing ? 'Edit role' : 'Create role'} description="System roles are locked; custom roles can be edited by the super administrator." footer={<div className="flex justify-end gap-3"><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={() => save.mutate()} disabled={save.isPending || !name.trim()}>Save</Button></div>}><div className="space-y-4"><div><Label htmlFor="role-name">Role name</Label><Input id="role-name" value={name} onChange={(e) => setName(e.target.value)} placeholder="Whistleblowing reviewer" /></div>{!editing && <div><Label htmlFor="role-organization">Scope</Label><select id="role-organization" value={organizationId} onChange={(e) => setOrganizationId(e.target.value)} className="h-11 w-full rounded-lg border border-slate-200 bg-slate-50 px-4 text-sm"><option value="">Platform</option>{organizations.data?.map((organization) => <option key={organization.id} value={organization.id}>{organization.name}</option>)}</select></div>}<div><p className="mb-2 text-sm font-medium text-slate-800">Permissions</p><div className="grid gap-2 sm:grid-cols-2">{permissions.data?.filter((permission) => permission.isActive).map((permission) => <label key={permission.id} className="flex items-center gap-2 rounded-md border border-slate-200 px-3 py-2 text-xs text-slate-700"><input type="checkbox" checked={permissionIds.includes(permission.id)} onChange={(e) => setPermissionIds((current) => e.target.checked ? [...current, permission.id] : current.filter((id) => id !== permission.id))} />{permission.key}</label>)}</div></div><ActionError error={save.error} /></div></Sheet></Frame>;
}

export function AdminUsersPage(): ReactElement {
  const client = useQueryClient(); const q = useAdminQuery<AdminUser[]>('users', adminService.users); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<AdminUser | null>(null); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [name, setName] = useState(''); const [status, setStatus] = useState<'Active' | 'Suspended'>('Active');
  const save = useMutation({ mutationFn: () => editing ? adminService.updateUser(editing.id, { status, displayName: name }) : adminService.createUser({ email: email.trim(), password, displayName: name.trim() || undefined }), onSuccess: () => { void client.invalidateQueries({ queryKey: ['platform-admin', 'users'] }); setOpen(false); setEditing(null); setEmail(''); setPassword(''); setName(''); setStatus('Active'); } }); const startCreate = () => { setEditing(null); setEmail(''); setPassword(''); setName(''); setStatus('Active'); setOpen(true); }; const startEdit = (row: AdminUser) => { setEditing(row); setEmail(row.email); setPassword(''); setName(row.displayName ?? ''); setStatus(row.status === 'Suspended' ? 'Suspended' : 'Active'); setOpen(true); };
  return <Frame eyebrow="System Console" title="Users" subtitle="Manage platform users, status, organization membership, and portal roles." action={<Button className="gap-1" onClick={startCreate}><Plus className="h-4 w-4" />Create user</Button>}><State loading={q.isLoading} error={q.error}>{q.data && <Table><TableHead><th className="px-4 py-3">User</th><th className="px-4 py-3">Roles</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Organizations</th><th className="px-4 py-3">Created</th><th className="px-4 py-3 text-right">Actions</th></TableHead><tbody className="divide-y divide-slate-100">{q.data.map((row) => <tr key={row.id} className="hover:bg-slate-50"><td className="px-4 py-3"><p className="font-medium text-slate-900">{row.displayName ?? '—'}</p><p className="text-xs text-slate-400">{row.email}</p></td><td className="px-4 py-3"><div className="flex flex-wrap gap-1">{row.roles.map((role) => <RoleBadge key={role} role={role} />)}</div></td><td className="px-4 py-3"><Badge variant={row.status === 'Active' ? 'success' : 'danger'}>{row.status}</Badge></td><td className="px-4 py-3 text-slate-600">{row.organizations}</td><td className="px-4 py-3 text-slate-500">{new Date(row.createdAt).toLocaleDateString()}</td><td className="px-4 py-3 text-right"><Button size="sm" variant="outline" onClick={() => startEdit(row)}><Edit3 className="h-3.5 w-3.5" />Edit</Button></td></tr>)}</tbody></Table>}</State><Sheet isOpen={open} onClose={() => setOpen(false)} title={editing ? 'Edit user' : 'Create user'} footer={<div className="flex justify-end gap-3"><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={() => save.mutate()} disabled={save.isPending || (!editing && (!email.trim() || password.length < 12))}>{save.isPending ? 'Saving...' : 'Save'}</Button></div>}><div className="space-y-4"><div><Label htmlFor="user-name">Display name</Label><Input id="user-name" value={name} onChange={(e) => setName(e.target.value)} /></div>{!editing && <><div><Label htmlFor="user-email">Email</Label><Input id="user-email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} /></div><div><Label htmlFor="user-password">Temporary password</Label><Input id="user-password" type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="At least 12 characters" /></div></>}{editing && <div><Label htmlFor="user-status">Status</Label><select id="user-status" value={status} onChange={(e) => setStatus(e.target.value as 'Active' | 'Suspended')} className="h-11 w-full rounded-lg border border-slate-200 bg-slate-50 px-4 text-sm"><option>Active</option><option>Suspended</option></select></div>}<ActionError error={save.error} /></div></Sheet></Frame>;
}

function LockedResourcePage({ title, subtitle, description }: { title: string; subtitle: string; description: string }): ReactElement { return <Frame eyebrow="System Console" title={title} subtitle={subtitle} action={<Badge variant="warning"><Lock className="mr-1 h-3 w-3" />Locked in standalone schema</Badge>}><div className="rounded-lg border border-slate-200 bg-white p-6"><p className="text-sm leading-6 text-slate-600">{description}</p><p className="mt-3 text-xs text-slate-400">The super-admin route is available, but this Whistleblowing database does not contain Civorah’s licensing/configuration persistence for this resource.</p></div></Frame>; }
export function AdminPlansPage(): ReactElement { const q = useAdminQuery('plans', adminService.plans); return <State loading={q.isLoading} error={q.error}><LockedResourcePage title="Licensing Plans" subtitle="Review plan definitions and entitlements." description="Licensing plans are controlled by the Civorah platform catalog and are not editable in this standalone Whistleblowing database." /></State>; }
export function AdminConfigPacksPage(): ReactElement { const q = useAdminQuery('config-packs', adminService.configPacks); return <State loading={q.isLoading} error={q.error}><LockedResourcePage title="Config Packs" subtitle="Review reusable organization configuration packs." description="Configuration packs require Civorah’s platform configuration store and remain locked here." /></State>; }
export function AdminCapabilitiesPage(): ReactElement { const q = useAdminQuery<AdminPermission[]>('capabilities', adminService.capabilities); return <Frame eyebrow="System Console" title="Capabilities" subtitle="Permission capabilities available in the standalone deployment." action={<Badge variant="warning"><Lock className="mr-1 h-3 w-3" />Catalog view</Badge>}><State loading={q.isLoading} error={q.error}>{q.data && <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{q.data.map((row) => <article key={row.id} className="rounded-lg border border-slate-200 bg-white p-4"><p className="text-sm font-semibold text-slate-900">{row.resource}</p><p className="mt-1 text-xs text-slate-500">{row.action}</p><p className="mt-3 font-mono text-[11px] text-brand-accent">{row.key}</p></article>)}</div>}</State></Frame>; }
export function AdminSettingsPage(): ReactElement { const q = useAdminQuery<AdminSettings>('settings', adminService.settings); return <Frame eyebrow="System Console" title="Settings" subtitle="Platform configuration and live deployment information." action={<Badge variant="warning"><Lock className="mr-1 h-3 w-3" />Read-only</Badge>}><State loading={q.isLoading} error={q.error}>{q.data && <div className="grid gap-4 lg:grid-cols-2"><section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="text-sm font-semibold text-slate-900">System information</h2><dl className="mt-4 divide-y divide-slate-100">{[['Product', q.data.product], ['Environment', q.data.apiEnvironment]].map(([label, value]) => <div key={label} className="flex justify-between gap-4 py-3 text-sm"><dt className="text-slate-500">{label}</dt><dd className="font-medium text-slate-800">{value}</dd></div>)}</dl></section><section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="text-sm font-semibold text-slate-900">Live totals</h2><dl className="mt-4 divide-y divide-slate-100">{[['Organizations', q.data.organizations], ['Users', q.data.users], ['Whistleblowing cases', q.data.cases]].map(([label, value]) => <div key={String(label)} className="flex justify-between gap-4 py-3 text-sm"><dt className="text-slate-500">{label}</dt><dd className="font-semibold text-brand-accent">{String(value)}</dd></div>)}</dl></section></div>}</State></Frame>; }
